Feature/benchmark
p2pderivatives/rust-bitcoin-coin-selection pull request #15
Opened 2022-12-22 19:57 UTC by yancyribbens

This PR closes https://github.com/p2pderivatives/rust-bitcoin-coin-selection/issues/2

The benchmark I added matches the benchmark in Bitcoin Core so an accurate comparison can be made.  The current results for this benchmark:

```
test benches::bench_select_coins_bnb ... bench:   1,234,158 ns/iter (+/- 523)`
```

I also ran the benchmark for Bitcoin Core to see how it stacks up:
```
|               ns/op |                op/s |    err% |     total | benchmark
|--------------------:|--------------------:|--------:|----------:|:----------
|        1,021,008.00 |              979.42 |    4.9% |      0.01 | `CoinSelection`
```

It seems that the current rust implementation is ~200 ns slower, although I can think of some optimizations that can bring the results closer :nerd_face: .

2022-12-23 00:40 UTC, Tibo-lg requested changes
Small nits otherwise looks good thanks!

2022-12-23 00:40 UTC, Tibo-lg commented on src/lib.rs
> +        utxo_pool.push(u);
```suggestion
        let u = MinimalUtxo { value: 1000 * COIN };
        let mut utxo_pool = vec![u; 1000];
        utxo_pool.push(MinimalUtxo { value: 3 * COIN });
```

2022-12-23 00:40 UTC, Tibo-lg commented on src/lib.rs
> +            assert_eq!(3 * COIN, result[1].value);
The asserts are slowing down the benchmark, IMHO the point is not to test here so I think it's better to remove them.

2022-12-23 01:11 UTC, Tibo-lg commented on src/lib.rs
> +            assert_eq!(3 * COIN, result[1].value);
Never mind I checked again and it doesn't seem to have any impact actually.

2022-12-23 18:49 UTC, yancyribbens commented
Thanks @Tibo-lg, should be good now.

2022-12-23 20:56 UTC, tcharding approved these changes
ACK 15d8f5ef05ee03d9258cdf3fe2963a31276b0b7d

2022-12-25 23:57 UTC, Tibo-lg commented
@yancyribbens I think you need to rebase after it's good to merge

2022-12-26 11:22 UTC, merged